import { getGeminiClient } from './client.js';
import { geminiQueue } from './queue.js';
import { config } from '../config.js';
import { SYSTEM_PROMPT_ILLUSTRATION, USER_PROMPT_ILLUSTRATION } from './prompts.js';

export const generateIllustrationBuffer = async ({ word, meaning }) => geminiQueue.run(async () => {
  const ai = getGeminiClient();
  const response = await ai.models.generateContent({
    model: config.models.image,
    contents: `${SYSTEM_PROMPT_ILLUSTRATION}\n\n${USER_PROMPT_ILLUSTRATION}\n\nword:${word}\nmeaning_ko:${meaning}`,
    config: { responseModalities: ['IMAGE'] }
  });

  const candidates = response?.candidates || [];
  for (const c of candidates) {
    for (const p of c?.content?.parts || []) {
      if (p.inlineData?.data) return Buffer.from(p.inlineData.data, 'base64');
    }
  }
  throw new Error('No image generated by Gemini');
});
